### ISSUE TITLE
Order Address Fields don't pull any data

### ISSUE THREAD

**Issue by JJGraphics** [DripEmail/magento-m2-extension#16]
Address_1 and Address_2 and Zip fields don't pull data for billing and shipping addresses from Magento 2.3.2. The data exists in Magento, but your extension seems be either looking in the wrong place, or calling it by the wrong name.

**Comment by will-in-wi** [comment]
Sorry for the long response, we missed this somehow.

I think this is fixed as of 1.7.6. https://github.com/DripEmail/magento-m2-extension/commit/5e5813ea0cd9cfe5182e274a80d09c0ba67e56e9

Could you upgrade and see whether this is resolved for you?

Thanks!

**Comment by JJGraphics** [comment]
Thanks for the update on this!

 

I’m up to 1.8.2 right now so I’ll take a look and make sure all is well.

 

Anything serious I should know about with 1.8.3 you guys just posted today?

**Comment by will-in-wi** [comment]
1.8.3 has fixes for abandoned cart URLs and virtual products. https://github.com/DripEmail/magento-m2-extension/blob/master/CHANGELOG.md

**Comment by JJGraphics** [comment]
Hi William,

 

What happens if we “cancel” an order in Magento 2 after it is already sync’d into Drip? Will it still trigger workflows, segments, etc? What about things like lifetime value in drip? Does it all get backed out?

 

Thanks!

Justin Broome

J & J Graphics and Design

O: 734-453-0697

F: 866-654-3581

**Comment by will-in-wi** [comment]
It _should_ sync a cancel event and decrement LTV accordingly. I _think_ (but am not sure) that you could even trigger workflows based on order cancellation.

If you aren't seeing this behavior, we can take a look.

**Comment by JJGraphics** [comment]
It DOES sync the cancel event and adjusts LTV but segments and workflows based on “placed an order” still trigger and there’s no way to filter them out. That seems problematic. An order with the status of “cancelled” should only trigger workflows looking for the Magento trigger of “Cancelled an order” Otherwise, drip still treats it like a live order, which it clearly is not.

**Comment by will-in-wi** [comment]
@JJGraphics I'm not very expert in the exact interaction with the workflows. Do you have a ticket filed with support at this point? Some of our support folks would have a better overall understanding.

**Comment by JJGraphics** [comment]
FYI, I opened 2 more issues here on github.
