### ISSUE TITLE
Order Fulfilled status

### ISSUE THREAD

**Issue by JJGraphics** [DripEmail/magento-m2-extension#57]
Order status of "fulfilled" (order shipped) isn't imported into drip when you sync orders. It is only updated on new orders in real time when you ship an order. That means in drip segments the event of "order fulfilled" can't be used to trigger anything from legacy orders.

**Comment by will-in-wi** [comment]
Would you file this as an issue with Drip's general support? These issues queues are mostly for tickets which have already debugged the code and identified where the issue is.

I'll work on making that clearer in this repo.

Thanks!
