### ISSUE TITLE
Changes to orders aren't sync'd

### ISSUE THREAD

**Issue by JJGraphics** [DripEmail/magento-m2-extension#58]
If an order in M2 is changed after it has initially sync'd to drip, the changes aren't sync'd back to drip. Examples: Change a shipping address, shipping method, product qty or even add/remove products. None of those "changes" make their way to drip.

**Comment by will-in-wi** [comment]
Would you file this as an issue with Drip's general support? These issues queues are mostly for tickets which have already debugged the code and identified where the issue is.

I'll work on making that clearer in this repo.

Thanks!

**Comment by will-in-wi** [comment]
Would you file this as an issue with Drip's general support? These issues queues are mostly for tickets which have already debugged the code and identified where the issue is.

I'll work on making that clearer in this repo.

Thanks!
